# eslint configuration
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    # support redux shallow copy
    impliedStrict: true
    experimentalObjectRestSpread: true
env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  comma-dangle:
    - error
    - objects: never
  arrow-parens:
    - error
    - always